spring:
      data:
           mongodb:
                 host: localhost
                 port: 27017
                 database: rest

logging:
      level:
           org.springframework.data: debug
           level: error